language: node_js
sudo: false
dist: trusty
before_install:
  - echo "Installing libvips..."
  - sudo add-apt-repository -y ppa:lovell/trusty-backport-vips
  - sudo apt-get update
  - sudo apt-get install -y libvips-dev
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
  - "6"
  - "7"
